/**
 * Seed script — popula o admin com dados de exemplo.
 * Rodar: npx tsx scripts/seed.ts
 */

import { writeFileSync } from "fs";
import { join } from "path";

const DATA_DIR = join(process.cwd(), "data");

const candidaturas = [
  {
    id: "c1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6",
    criadoEm: "2025-03-05T10:30:00.000Z",
    status: "nova",
    nome: "Ricardo Almeida",
    email: "ricardo.almeida@example.com",
    telefone: "+351 912 345 678",
    pais: "Portugal",
    cidade: "Lisboa",
    perfil: "operador",
    experiencia: "15 anos em gestao de restaurantes e food service. Operei 3 restaurantes proprios em Lisboa e 2 franquias de marcas internacionais. Experiencia com delivery via Glovo e UberEats.",
    setor: "food-service",
    empresaAtual: "Sabores Lda.",
    linkedin: "https://linkedin.com/in/ricardoalmeida",
    modelo: ["strike-studio", "nexial-e-brand"],
    capitalDisponivel: "30k-50k",
    prazo: "1-3-meses",
    dedicacao: "integral",
    motivacao: "Quero expandir minha atuacao para o fitness e e-commerce. O modelo do +351 que integra fisico e digital e exatamente o que procuro.",
    diferenciais: "Rede de contactos com 50+ empresarios em Lisboa. Experiencia comprovada em gestao de equipes de 20+ pessoas. Conheco profundamente o mercado local.",
    disponibilidade: "Segunda a sexta, 9h-18h",
    aceitaNDA: true,
  },
  {
    id: "d2b3c4d5-e6f7-a8b9-c0d1-e2f3a4b5c6d7",
    criadoEm: "2025-03-07T14:15:00.000Z",
    status: "em-analise",
    nome: "Ana Beatriz Santos",
    email: "ana.santos@example.com",
    telefone: "+55 21 99876 5432",
    pais: "Brasil",
    cidade: "Rio de Janeiro",
    perfil: "investidor",
    experiencia: "Investidora anjo com portfolio de 8 startups. Saida bem-sucedida em 2 (fintech e edtech). Background em consultoria McKinsey. MBA em Wharton.",
    setor: "financeiro",
    empresaAtual: "ABS Capital",
    linkedin: "https://linkedin.com/in/anabsantos",
    modelo: ["nexial-gso", "nexial-e-brand"],
    capitalDisponivel: "100k-250k",
    prazo: "3-6-meses",
    dedicacao: "passivo",
    motivacao: "Interesse em exposicao ao mercado europeu com tese clara. O modelo de consultoria IA + e-commerce e escalavel. Quero um veiculo de investimento com governanca real.",
    diferenciais: "Capital paciente + rede de mentores e investidores no Brasil e EUA. Posso trazer co-investidores para rodadas futuras.",
    disponibilidade: "Flexivel, prefiro video-chamadas",
    aceitaNDA: true,
    notas: "Perfil muito forte. Agendar call com Henrique esta semana.",
    atribuidoA: "Henrique Lemos",
  },
  {
    id: "e3c4d5e6-f7a8-b9c0-d1e2-f3a4b5c6d7e8",
    criadoEm: "2025-03-09T09:45:00.000Z",
    status: "nova",
    nome: "Tomas Ferreira",
    email: "tomas.f@example.com",
    telefone: "+351 933 456 789",
    pais: "Portugal",
    cidade: "Cascais",
    perfil: "ambos",
    experiencia: "Designer industrial com 8 anos de experiencia. Trabalho com impressao 3D ha 4 anos, tenho farm propria com 6 Bambu P1S. Ja vendi 2000+ pecas no Etsy.",
    setor: "manufatura",
    empresaAtual: "Freelancer",
    modelo: ["farmlab-3d"],
    capitalDisponivel: "10k-30k",
    prazo: "imediato",
    dedicacao: "integral",
    motivacao: "Vivo em Cascais e trabalho com 3D printing. O FarmLab 3D e literalmente o meu negocio ideal. Quero profissionalizar e escalar o que ja faco.",
    diferenciais: "Farm operacional, experiencia em design para FDM/SLA, carteira de clientes existente, dominio do Bambu Studio e slicing avancado.",
    disponibilidade: "Qualquer dia, moro em Cascais",
    aceitaNDA: true,
  },
  {
    id: "f4d5e6f7-a8b9-c0d1-e2f3-a4b5c6d7e8f9",
    criadoEm: "2025-03-10T16:20:00.000Z",
    status: "entrevista",
    nome: "Maria Clara Vieira",
    email: "mariaclara@example.com",
    telefone: "+351 966 789 012",
    pais: "Portugal",
    cidade: "Porto",
    perfil: "operador",
    experiencia: "10 anos em e-commerce. Montei e vendi 2 lojas online (moda feminina e acessorios). Experiencia com sourcing da China via Alibaba e 1688.",
    setor: "importacao",
    empresaAtual: "",
    linkedin: "https://linkedin.com/in/mariaclarav",
    modelo: ["nexial-global", "nexial-e-brand"],
    capitalDisponivel: "50k-100k",
    prazo: "1-3-meses",
    dedicacao: "integral",
    motivacao: "Tenho experiencia direta com importacao China-Europa e quero um modelo com estrutura. Nexial Global e o tipo de negocio que sei operar. O E-Brand me interessa como canal de distribuicao.",
    diferenciais: "Contactos com 15+ fornecedores verificados na China. Experiencia com despacho aduaneiro PT. Sei montar e otimizar lojas Shopify.",
    disponibilidade: "Terca e quinta, manha",
    aceitaNDA: true,
    notas: "Excelente perfil para Nexial Global. Entrevista presencial marcada para 15/03.",
    atribuidoA: "Fernando Vieira",
  },
];

const contatos = [
  {
    id: "ct1-a2b3-c4d5-e6f7-a8b9c0d1e2f3",
    criadoEm: "2025-03-04T11:00:00.000Z",
    lido: true,
    arquivado: false,
    nome: "Pedro Goncalves",
    email: "pedro.g@example.com",
    empresa: "DigitalFlow Agency",
    tipo: "fornecedor",
    mensagem: "Somos uma agencia de marketing digital em Lisboa e gostariamos de apresentar nossos servicos ao Grupo +351. Temos experiencia com marcas B2C e e-commerce.",
    notas: "Contactar quando precisarmos de agencia para Nexial E-Brand",
  },
  {
    id: "ct2-b3c4-d5e6-f7a8-b9c0d1e2f3a4",
    criadoEm: "2025-03-08T08:30:00.000Z",
    lido: false,
    arquivado: false,
    nome: "Sofia Martins",
    email: "sofia.m@example.com",
    empresa: "",
    tipo: "parceria",
    orcamento: "a-definir",
    mensagem: "Sou instrutora de artes marciais no Porto e vi o projeto Strike Studio. Tenho interesse em entender melhor o modelo de franquia. Posso disponibilizar o meu espaco como piloto.",
  },
  {
    id: "ct3-c4d5-e6f7-a8b9-c0d1e2f3a4b5",
    criadoEm: "2025-03-10T18:45:00.000Z",
    lido: false,
    arquivado: false,
    nome: "Carlos Henrique Souza",
    email: "carlos.hs@example.com",
    empresa: "CH Importacoes",
    tipo: "joint-venture",
    orcamento: "50k-200k",
    mensagem: "Trabalho com importacao de equipamentos industriais da China. Tenho interesse na Nexial Global. Posso trazer know-how de supply chain e contactos com fornecedores em Yiwu e Guangzhou.",
  },
];

writeFileSync(join(DATA_DIR, "candidaturas.json"), JSON.stringify(candidaturas, null, 2));
writeFileSync(join(DATA_DIR, "contatos.json"), JSON.stringify(contatos, null, 2));

console.log("Seed concluido:");
console.log(`  ${candidaturas.length} candidaturas`);
console.log(`  ${contatos.length} contatos`);
