/**
 * Seed script — popula o admin com dados de exemplo.
 * Rodar: npx tsx scripts/seed.ts
 */

import { writeFileSync } from "fs";
import { join } from "path";

const DATA_DIR = join(process.cwd(), "data");

const candidaturas = [
  {
    id: "c1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6",
    criadoEm: "2025-03-05T10:30:00.000Z",
    status: "nova",
    nome: "Ricardo Almeida",
    email: "ricardo.almeida@example.com",
    telefone: "+351 912 345 678",
    pais: "Portugal",
    cidade: "Lisboa",
    perfil: "operador",
    experiencia: "15 anos em gestão de restaurantes e food service. Operei 3 restaurantes próprios em Lisboa e 2 franquias de marcas internacionais. Experiência com delivery via Glovo e UberEats.",
    setor: "food-service",
    empresaAtual: "Sabores Lda.",
    linkedin: "https://linkedin.com/in/ricardoalmeida",
    modelo: ["veeenha", "barbearia-do-rao"],
    capitalDisponivel: "30k-50k",
    prazo: "1-3-meses",
    dedicacao: "integral",
    motivacao: "Quero expandir minha atuação para o digital mantendo a operação física. O modelo FIGITAL do +351 é exatamente o que procuro — integrar o que já sei fazer com tecnologia.",
    diferenciais: "Rede de contactos com 50+ restaurantes em Lisboa. Experiência comprovada em gestão de equipes de 20+ pessoas. Conheço profundamente o mercado local de food service.",
    disponibilidade: "Segunda a sexta, 9h-18h",
    aceitaNDA: true,
  },
  {
    id: "d2b3c4d5-e6f7-a8b9-c0d1-e2f3a4b5c6d7",
    criadoEm: "2025-03-07T14:15:00.000Z",
    status: "em-analise",
    nome: "Ana Beatriz Santos",
    email: "ana.santos@example.com",
    telefone: "+55 21 99876 5432",
    pais: "Brasil",
    cidade: "Rio de Janeiro",
    perfil: "investidor",
    experiencia: "Investidora anjo com portfólio de 8 startups. Saída bem-sucedida em 2 (fintech e edtech). Background em consultoria McKinsey. MBA em Wharton.",
    setor: "financeiro",
    empresaAtual: "ABS Capital",
    linkedin: "https://linkedin.com/in/anabsantos",
    modelo: ["ruptfy", "cortex-fc", "long-view"],
    capitalDisponivel: "100k-250k",
    prazo: "3-6-meses",
    dedicacao: "passivo",
    motivacao: "Interesse em exposição ao mercado europeu com tese clara. O modelo de infoproduto + plataforma é escalável e conheço o mercado edtech. Quero um veículo de investimento com governança real.",
    diferenciais: "Capital paciente + rede de mentores e investidores no Brasil e EUA. Posso trazer co-investidores para rodadas futuras.",
    disponibilidade: "Flexível, prefiro vídeo-chamadas",
    aceitaNDA: true,
    notas: "Perfil muito forte. Agendar call com Henrique esta semana.",
    atribuidoA: "Henrique Lemos",
  },
  {
    id: "e3c4d5e6-f7a8-b9c0-d1e2-f3a4b5c6d7e8",
    criadoEm: "2025-03-09T09:45:00.000Z",
    status: "nova",
    nome: "Tomás Ferreira",
    email: "tomas.f@example.com",
    telefone: "+351 933 456 789",
    pais: "Portugal",
    cidade: "Cascais",
    perfil: "ambos",
    experiencia: "Designer industrial com 8 anos de experiência. Trabalho com impressão 3D há 4 anos, tenho farm própria com 6 Bambu P1S. Já vendi 2000+ peças no Etsy.",
    setor: "manufatura",
    empresaAtual: "Freelancer",
    modelo: ["forge-and-flow-3d"],
    capitalDisponivel: "10k-30k",
    prazo: "imediato",
    dedicacao: "integral",
    motivacao: "Vivo em Cascais e trabalho com 3D printing. O Forge and Flow é literalmente o meu negócio ideal. Quero profissionalizar e escalar o que já faço.",
    diferenciais: "Farm operacional, experiência em design para FDM/SLA, carteira de clientes existente, domínio do Bambu Studio e slicing avançado.",
    disponibilidade: "Qualquer dia, moro em Cascais",
    aceitaNDA: true,
  },
  {
    id: "f4d5e6f7-a8b9-c0d1-e2f3-a4b5c6d7e8f9",
    criadoEm: "2025-03-10T16:20:00.000Z",
    status: "entrevista",
    nome: "Maria Clara Vieira",
    email: "mariaclara@example.com",
    telefone: "+351 966 789 012",
    pais: "Portugal",
    cidade: "Porto",
    perfil: "operador",
    experiencia: "10 anos em e-commerce. Montei e vendi 2 lojas online (moda feminina e acessórios). Experiência com sourcing da China via Alibaba e 1688.",
    setor: "importacao",
    empresaAtual: "",
    linkedin: "https://linkedin.com/in/mariaclarav",
    modelo: ["purple-party", "veeenha"],
    capitalDisponivel: "50k-100k",
    prazo: "1-3-meses",
    dedicacao: "integral",
    motivacao: "Tenho experiência direta com importação China-Europa e quero um modelo com estrutura. Purple Party é o tipo de negócio que sei operar. O Veeenha me interessa como canal de distribuição.",
    diferenciais: "Contactos com 15+ fornecedores verificados na China. Experiência com despacho aduaneiro PT. Sei montar e otimizar lojas Shopify.",
    disponibilidade: "Terça e quinta, manhã",
    aceitaNDA: true,
    notas: "Excelente perfil para Purple Party. Entrevista presencial marcada para 15/03.",
    atribuidoA: "Fernando Vieira",
  },
];

const contatos = [
  {
    id: "ct1-a2b3-c4d5-e6f7-a8b9c0d1e2f3",
    criadoEm: "2025-03-04T11:00:00.000Z",
    lido: true,
    arquivado: false,
    nome: "Pedro Gonçalves",
    email: "pedro.g@example.com",
    empresa: "DigitalFlow Agency",
    tipo: "fornecedor",
    mensagem: "Somos uma agência de marketing digital em Lisboa e gostaríamos de apresentar nossos serviços ao Grupo +351. Temos experiência com marcas B2C e e-commerce.",
    notas: "Contactar quando precisarmos de agência para Veeenha",
  },
  {
    id: "ct2-b3c4-d5e6-f7a8-b9c0d1e2f3a4",
    criadoEm: "2025-03-08T08:30:00.000Z",
    lido: false,
    arquivado: false,
    nome: "Sofia Martins",
    email: "sofia.m@example.com",
    empresa: "",
    tipo: "parceria",
    orcamento: "a-definir",
    mensagem: "Sou proprietária de 2 barbearias no Porto e vi o projeto Barbearia do Rão. Tenho interesse em entender melhor o modelo. Posso disponibilizar os meus espaços como pilotos.",
  },
  {
    id: "ct3-c4d5-e6f7-a8b9-c0d1e2f3a4b5",
    criadoEm: "2025-03-10T18:45:00.000Z",
    lido: false,
    arquivado: false,
    nome: "Carlos Henrique Souza",
    email: "carlos.hs@example.com",
    empresa: "CH Importações",
    tipo: "joint-venture",
    orcamento: "50k-200k",
    mensagem: "Trabalho com importação de equipamentos industriais do China. Tenho interesse na Purple Party. Posso trazer know-how de supply chain e contactos com fornecedores em Yiwu e Guangzhou.",
  },
];

writeFileSync(join(DATA_DIR, "candidaturas.json"), JSON.stringify(candidaturas, null, 2));
writeFileSync(join(DATA_DIR, "contatos.json"), JSON.stringify(contatos, null, 2));

console.log("Seed concluído:");
console.log(`  ${candidaturas.length} candidaturas`);
console.log(`  ${contatos.length} contatos`);
